# Generated by Django 5.0.4 on 2024-04-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_remove_customuser_is_writer_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='Are you a parent'),
        ),
    ]
